### ISSUE TITLE
Documentation and ambitions?

### ISSUE THREAD

**Issue by fuzzy76** [illicitonion/slackbridge#2]
For non-Go developers, can you add a short readme? And do you intend to continue supporting this code?

**Comment by shwaydogg** [comment]
Yes, what is the goal of this project?

**Comment by illicitonion** [comment]
The goal of this project was largely for me to experiment with the Matrix APIs in Go, as well as find some problems and edge-cases you run into when bridging different chat protocols with them not helping you. It's now dormant, and definitely isn't functional enough to use in anger. I probably wouldn't bother looking at it very much. Otherwise, https://github.com/matrix-org/matrix-appservice-slack looks like it's actually getting some love.
